services:
  lightrag:
    networks:
      - proxy
      - backend
    volumes:
      - ./secrets:/run/secrets:ro
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.rag.rule: "Host(`rag.${DOMAIN_NAME}`)"
      traefik.http.routers.rag.entrypoints: "websecure"
      traefik.http.routers.rag.tls.certresolver: "mytlschallenge"
      traefik.http.services.rag.loadbalancer.server.port: "9621"
      traefik.http.routers.rag.middlewares: "rag-auth,secure-headers,rag-ratelimit"
      traefik.http.middlewares.rag-auth.basicauth.usersfile: "/run/secrets/traefik_basicauth"
      # Ensure a file at ./secrets/traefik_basicauth exists with htpasswd content for basic auth
      traefik.http.middlewares.secure-headers.headers.stsSeconds: "15552000"
      traefik.http.middlewares.secure-headers.headers.frameDeny: "true"
      traefik.http.middlewares.secure-headers.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.secure-headers.headers.browserXssFilter: "true"
      traefik.http.middlewares.rag-ratelimit.ratelimit.average: "50"
      traefik.http.middlewares.rag-ratelimit.ratelimit.burst: "100"

networks:
  proxy:
    external: true
    name: proxy
  backend:
    external: true
    name: backend
