name: Build and push postgres-pgvector

on:
  push:
    # allow pushes from feature branches and the date-stamped branch we use during testing
    branches:
      - feat/ansible-smoke-ci
      - feat/ansible-smoke-ci-2025-09-17-1
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Default registry is GHCR. To use a different registry, change this value or
      # add a secret REGISTRY_URL and update this workflow accordingly.
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Ensure the build context directory is checked out even when sparse checkout is used
          fetch-depth: 0
          # Do not use partial 'paths' checkout (not supported here); fetch full history

      - name: Set REGISTRY from secret or default
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: |
          # Use the step-level env to safely access the secret in the script.
          if [ -n "$REGISTRY_URL" ]; then
            echo "REGISTRY=$REGISTRY_URL" >> $GITHUB_ENV
          else
            echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Ensure build context is present
        # Force a non-shallow fetch of the exact commit and disable sparse checkout
        run: |
          echo "Checking for infra/postgres-pgvector..."
          if [ -d infra/postgres-pgvector ]; then
            echo "Build context already present"
            ls -la infra/postgres-pgvector || true
            exit 0
          fi
          echo "infra/postgres-pgvector not found — performing full fetch of commit $GITHUB_SHA"
          # Fetch the exact commit (no --depth) so files are available
          git -c protocol.version=2 fetch --no-tags --prune origin $GITHUB_SHA || true
          # Disable sparse checkout if enabled
          git sparse-checkout disable || true
          # Ensure working tree matches the commit we intend to build
          git checkout --force $GITHUB_SHA || true
          echo "After checkout:"; ls -la infra || true
        shell: bash

      - name: Debug: list infra directory
        run: |
          echo "Listing infra:"; ls -la infra || true
          echo "Listing infra/postgres-pgvector:"; ls -la infra/postgres-pgvector || true
        shell: bash

      - name: Full clone and copy build context (fallback)
        run: |
          echo "Performing authenticated shallow clone into /tmp/fullrepo to ensure build context is available"
          rm -rf /tmp/fullrepo || true
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" /tmp/fullrepo --depth=1 || true
          if [ -d /tmp/fullrepo/infra/postgres-pgvector ]; then
            mkdir -p infra
            rm -rf infra/postgres-pgvector || true
            cp -a /tmp/fullrepo/infra/postgres-pgvector ./infra/
            echo "Copied infra/postgres-pgvector from full clone"
            ls -la infra/postgres-pgvector || true
          else
            echo "Fallback clone did not contain infra/postgres-pgvector"
            ls -la /tmp/fullrepo/infra || true
            exit 1
          fi
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry (defaults to GHCR)
        uses: docker/login-action@v2
        # By default we authenticate to GHCR using the automatically provided
        # `GITHUB_TOKEN` and the current actor. This is suitable for pushing
        # packages in this repository. If you want to push to a different
        # registry, set the `REGISTRY_URL` secret and add `REGISTRY_USERNAME`/
        # `REGISTRY_PASSWORD` (or a PAT) to repository secrets and update this
        # step to use those secrets instead.
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        id: buildpush
        with:
          context: ./infra/postgres-pgvector
          file: ./infra/postgres-pgvector/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/postgres-pgvector:15
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/postgres-pgvector:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/postgres-pgvector:${{ github.sha }}

      - name: Set outputs
        run: |
          echo "image=${{ env.REGISTRY }}/${{ github.repository_owner }}/postgres-pgvector:${{ github.sha }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Verify image (smoke)
        run: |
          echo "Image pushed: ${{ env.REGISTRY }}/${{ github.repository_owner }}/postgres-pgvector:${{ github.sha }}"
