name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install & Build & Test
        run: |
          cd dashboard/frontend
          npm ci --prefer-offline
          npm run build --if-present
          npm test --if-present

      - name: CI pre-push mirror (typecheck + tests)
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          cd dashboard/frontend
          npm ci --prefer-offline
          npm run typecheck --if-present
          npm test --if-present

  e2e-smoke:
    needs: build-and-test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          cd dashboard/frontend
          npm ci --prefer-offline

      - name: Install Playwright Browsers
        run: |
          cd dashboard/frontend
          npx playwright install --with-deps

      - name: Build frontend
        run: |
          cd dashboard/frontend
          npm run build --if-present

      - name: Start static server (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd dashboard/frontend
          nohup npm run serve-dist > serve.log 2>&1 &
          sleep 2
        shell: bash

      - name: Start static server (Windows)
        if: runner.os == 'Windows'
        run: |
          cd dashboard/frontend
          Start-Process -NoNewWindow -FilePath npm -ArgumentList 'run','serve-dist'
          Start-Sleep -Seconds 2
        shell: pwsh

      - name: Run Playwright smoke tests
        run: |
          cd dashboard/frontend
          npm run e2e --if-present

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install commitlint
        run: |
          cd dashboard/frontend
          npm ci --prefer-offline
      - name: Run commitlint on PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Running commitlint on pull request commits"
          git fetch --no-tags --prune --depth=1 origin +refs/pull/${{ github.event.number }}/merge
          git log --pretty=format:%B origin/HEAD..FETCH_HEAD | npx --no-install commitlint --verbose || true

  secret-scan:
    name: Secret scan (detect-secrets)
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install --user detect-secrets
          echo "Add $HOME/.local/bin to PATH via GITHUB_PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run detect-secrets scan using baseline
        id: detect
        run: |
          # run scan and capture output; exit code non-zero indicates new findings
          set -o pipefail
          detect-secrets scan --baseline .secrets.baseline --all-files > detect_output.json || true
          echo "::warning::detect-secrets completed; results written to detect_output.json"
          cat detect_output.json | jq '.results | length' > detect_count.txt || true

      - name: Create issue when new secrets found
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let out = {};
            try {
              out = JSON.parse(fs.readFileSync('detect_output.json','utf8') || '{}');
            } catch (e) {
              core.warning('Could not parse detect_output.json');
              out = {};
            }
            const findings = Object.keys((out.results) || {});
            if (!findings || findings.length === 0) {
              core.info('No new secrets detected');
              return;
            }
            // create a gist with the full output for triage
            const gistResp = await github.rest.gists.create({
              files: { 'detect_output.json': { content: JSON.stringify(out, null, 2) } },
              public: false,
              description: `detect-secrets output for ${context.repo.owner}/${context.repo.repo} @ ${process.env.GITHUB_SHA}`,
            });
            const gistUrl = gistResp.data.html_url;
            const body = ['New potential secrets detected when running detect-secrets against the baseline:', '', ...findings.map(f => `- ${f}`), '', `Full output: ${gistUrl}`].join('\n');
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `detect-secrets: new potential secrets found (${findings.length})`,
              body,
            });
            core.setFailed('New potential secrets detected; see created issue for details');
