name: Render Architecture Diagrams

on:
  push:
    paths:
      - 'docs/architecture/**'
  workflow_dispatch: {}

jobs:
  render:
    runs-on: ${{ matrix.os }}
    # NOTE: Windows runners do not support Docker service containers. We therefore
    # run this job only on Ubuntu and use a local Kroki service container there.
    services:
      kroki:
        image: yugabytelabs/kroki:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl -fsS http://localhost:8000/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=6
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (for potential tools)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java (for Structurizr CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make scripts executable (Unix)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x ./scripts/gen-diagrams.sh

      - name: Wait for local Kroki (Linux only)
        if: runner.os == 'Linux'
        run: |
          set -e
          echo "Waiting for kroki at http://localhost:8000/ ..."
          ATTEMPTS=12
          SLEEP=5
          i=0
          until curl -fsS http://localhost:8000/ >/dev/null 2>&1; do
            i=$((i+1))
            if [ $i -ge $ATTEMPTS ]; then
              echo "kroki did not become ready after $((ATTEMPTS * SLEEP))s"
              exit 1
            fi
            echo "kroki not ready yet, sleeping $SLEEP s (attempt $i/$ATTEMPTS)"
            sleep $SLEEP
          done
          echo "kroki is ready"

      - name: Download Structurizr CLI (latest)
        if: runner.os == 'Linux'
        run: |
          set -euxo pipefail
          WORKDIR="$(pwd)/.tools"
          mkdir -p "$WORKDIR"
          cd "$WORKDIR"
          echo "Downloading Structurizr CLI zip..."
          curl -fsSL -o structurizr-cli.zip \
            https://github.com/structurizr/cli/releases/latest/download/structurizr-cli.zip
          unzip -o structurizr-cli.zip
          # Find the jar produced by the zip (structurizr-cli-<ver>.jar)
          JAR_PATH=$(find . -maxdepth 2 -type f -name 'structurizr-cli-*.jar' | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "Could not locate structurizr-cli-*.jar after unzip" >&2
            exit 1
          fi
          echo "STRUCTURIZR_CLI_JAR=$WORKDIR/$JAR_PATH" >> $GITHUB_ENV

      - name: Run generator
        shell: bash
        env:
          KROKI_URL: http://localhost:8000
          STRUCTURIZR_CLI_JAR: ${{ env.STRUCTURIZR_CLI_JAR }}
        run: |
          ./scripts/gen-diagrams.sh

      - name: Upload diagram outputs
        uses: actions/upload-artifact@v4
        with:
          name: diagrams-${{ matrix.os }}
          path: docs/architecture/out

      # Optional: deploy to GitHub Pages if configured (uncomment to enable)
      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: docs/architecture/out
